### ISSUE TITLE
Transformed url giving http 400 error

### ISSUE THREAD

**Issue by jackiepapers** [djade007/cloudinary_public#10]
This url from Cloudinary works: `https://res.cloudinary.com/xxx/image/upload/s--KrQpnLn4--/c_thumb,w_200,g_face/v1/xxx/xxx.jpg`

This one returned by plugin give 400 error: `https://res.cloudinary.com/xxx/image/upload/c_thumb,g_face,w_200/s--q2NgOpl8--/v1617419988/xxx/xxx.jpg`

**Comment by djade007** [comment]
@jackiepapers can you provide the exact transformation code you used?

**Comment by jackiepapers** [comment]
`final cloudinaryImage = CloudinaryImage(user.imageUrl!);
    final String url = cloudinaryImage
        .transform()
        .width(100)
        .height(100)
        .gravity('face')
        .crop('thumb')
        .generate()!;`

This gives an error: `Another exception was thrown: HTTP request failed, statusCode: 400,`

The transform url looks different than ones generated in the Cloudinary console.

Cloudinary url: `https://res.cloudinary.com/[cloud_name]/image/upload/s--76pBIflG--/c_thumb,w_200,g_face/v1/[domain]/mddrzn4w1gsh9scqolx7.jpg`

Plugin url: `https://res.cloudinary.com/[cloud_name]/image/upload/c_thumb,g_face,h_150,w_150/s--ld2ao2Sk--/v1618431207/[domain]/uhy6yftvv7kzhlrsxvhn.jpg`

`The following assertion was thrown building:
Invalid cloudinary url
'package:cloudinary_public/src/transformation/cloudinary_image.dart':
Failed assertion: line 20 pos 12: 'resource.length == 2'

When the exception was thrown, this was the stack:
#2      new CloudinaryImage (package:cloudinary_public/src/transformation/cloudinary_image.dart:20:12)
#3      new CloudinaryImage.fromPublicId (package:cloudinary_public/src/transformation/cloudinary_image.dart:26:12)
#4      CloudinaryPublic.getImage (package:cloudinary_public/src/cloudinary_public.dart:45:28)
#5      UsersScreen._buildListTile (package:cleanconnect/screens/users/users_screen.dart:56:40)
#6      UsersScreen.build.<anonymous closure>.<anonymous closure> (package:cleanconnect/screens/users/users_screen.dart:33:24)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
#8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1201:28)
#9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1214:55)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
#11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1207:12)
#12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1894:59)
#14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
#15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1894:14)
#16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#17     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#20     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:512:13)
#24     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1570:12)
#25     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1479:20)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#39     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#40     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:925:7)
#41     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
#42     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:407:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#47     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1371:11)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#49     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#50     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:925:7)
#51     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
#52     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:407:14)
#53     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1641:7)
#54     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
#55     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#56     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
#57     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#58     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#59     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#60     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#64     _invoke (dart:ui/hooks.dart:161:10)
#65     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#66     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 5 frames from class _AssertionError and dart:async)`

**Comment by djade007** [comment]
Do you have `v1` as the name of any folder on Cloudinary?

**Comment by jackiepapers** [comment]
No.

**Comment by djade007** [comment]
> This url from Cloudinary works: `https://res.cloudinary.com/xxx/image/upload/s--KrQpnLn4--/c_thumb,w_200,g_face/v1/xxx/xxx.jpg`
> 
> This one returned by plugin give 400 error: `https://res.cloudinary.com/xxx/image/upload/c_thumb,g_face,w_200/s--q2NgOpl8--/v1617419988/xxx/xxx.jpg`

I can't seem to replicate this.

The first url contains `v1`. The second url shouldn't still have the version number `v1617419988` as the plugin strips that out automatically.

**Comment by djade007** [comment]
Can you post the content of `user.imageUrl` ?

**Comment by jackiepapers** [comment]
`https://res.cloudinary.com/xxx/image/upload/s--ld6ao2Fk--/v1617419988/cleanConnect/uhy2yvtvv7kzhlrspvhn.jpg`

**Comment by djade007** [comment]
I have seen the issue and currently working on a fix.  This value `s--ld6ao2Fk--` in the url looks strange, any idea on how it is being added?

**Comment by jackiepapers** [comment]
I created a new upload preset and now it works! Probably should have thought of that first.

**Comment by djade007** [comment]
oh ok. We can close this issue then.
