### ISSUE TITLE
Compression on video

### ISSUE THREAD

**Issue by pmrajani** [djade007/cloudinary_public#15]
Is this plugins provide compression tools? like i pick 30MB video and compressed it to 2 MB - 4MB

i can see official document provide this
[https://cloudinary.com/blog/how_to_automate_compression_of_video_files_with_one_line_of_code
](https://cloudinary.com/blog/how_to_automate_compression_of_video_files_with_one_line_of_code
) @djade007

**Comment by djade007** [comment]
Hello @pmrajani 

The article mentioned two compression techniques:
1. Compression before upload
2. Compression using the cloudinary API (After upload)

This package does not support the first technique, as it just uploads only. However, you can use an external plugin like https://pub.dev/packages/video_compress to compress the file before you upload.

The second technique is possible with this package:
`final url = cloudinaryImage.transform().quality('50').generate()`
