### ISSUE TITLE
[Question] Is there any way to submit context while uploading file?

### ISSUE THREAD

**Issue by JigneshPatel23** [djade007/cloudinary_public#17]
I am using this currently using `Dio`

```
final formData = FormData.fromMap({
    'file': await MultipartFile.fromFile(
          file.path,
     ),
    'upload_preset': upload_preset,
    'context': context,
});
```

**Comment by djade007** [comment]
The package uses [http plugin](https://pub.dev/packages/http) not dio

**Comment by JigneshPatel23** [comment]
Yes @djade007 understood this package is using http plugin and not dio.. 
I have shared dio code as a reference which I am currently using to upload file with context param on my app. 

I am looking for similar option on this package if any? 
If not available yet - any plan to add those in near future?

**Comment by djade007** [comment]
I see. I'll work on it today.

**Comment by djade007** [comment]
Hello @JigneshPatel23, the context option has been added to the package.

- Update to version: `^0.9.0`
- And can check [the example here](https://github.com/djade007/cloudinary_public/blob/d4788e562cfb4d01ca497309965a3729e4475adb/example/lib/src/image_picker_example.dart#L73)

**Comment by djade007** [comment]
You can also access the context after upload with: `CloudinaryResponse.customContext`

**Comment by JigneshPatel23** [comment]
Thanks much @djade007 for quick tern around and adding this feature 🎉🎉
