### ISSUE TITLE
Signed uploads

### ISSUE THREAD

**Issue by zs-adarsh** [djade007/cloudinary_public#19]
Hi, I was trying Cloudinary_public to upload media to my cloudinary bucket.  
It is working as intended for unsigned presets, but throws error for signed presets.
Any idea why this could be happening?
Thanks!

**Comment by iloveteajay** [comment]
I don't think you can use this package for signed uploads.

**Comment by iloveteajay** [comment]
Use this package instead [https://pub.dev/packages/cloudinary_sdk](Cloudinary SDK)

**Comment by iloveteajay** [comment]
Use this package instead https://pub.dev/packages/cloudinary_sdk

**Comment by djade007** [comment]
Cloudinary signed uploads will require you to upload with your secret key and it is not supported by this package.
