### ISSUE TITLE
Create video thumbnail while uploading video on cloudinary (Feature request)

### ISSUE THREAD

**Issue by pooja96km** [djade007/cloudinary_public#6]

**Comment by djade007** [comment]
@pooja96km to [generate video thumbnails](https://cloudinary.com/documentation/video_manipulation_and_delivery#generating_video_thumbnails) from Cloudinary you need have uploaded the video first.

If you want to get video thumbnails before the video has completely uploaded, you can try this Flutter package https://pub.dev/packages/video_thumbnail
