### ISSUE TITLE
Upload a chucked video when its more that 100mb

### ISSUE THREAD

**Issue by chaser79** [djade007/cloudinary_public#8]
Hello,

Ive look through this package and can't seem to find if it supports uploading of a video file of more than 100mb. When a video file is grater than 100mb you have to upload the video in chucks. Does this package support that or is it something that still needs to be implemented?

**Comment by djade007** [comment]
This package doesn't support chunk uploading yet.

**Comment by djade007** [comment]
Added in v0.20.0 from pr #24
