### ISSUE TITLE
Can't use MultiImagePicker lib

### ISSUE THREAD

**Issue by esDotDev** [djade007/cloudinary_public#9]
When using the MultiImagePicker plugin, we're getting this error when trying to call cloudinary.uploadFile()

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = 'content://media/external/images/media/89894'

The same code works fine with image_picker. When I compare the returned paths, I see this:
multi_image_picker: "content://media/external/images/media/89894"
image_picker: "data/user/0/com.example.example/cache/image_picker6683537466962246256.jpg"

So it appears as though image_picker makes some local copy, and is required for uploads to work?

**Comment by esDotDev** [comment]
Ah, it looks like using FlutterAbsolutePath.getAbsolutePath(paths) converts from the identifier into the real path and then it can be uploaded.
https://pub.dev/packages/flutter_absolute_path

**Comment by djade007** [comment]
@esDotDev I have tried the multi_image_picker example on both Android and iOS and they work, https://github.com/djade007/cloudinary_public/blob/master/example/lib/src/multi_image_picker_example.dart

Can you provide the example code you are trying and on what platform?

**Comment by esDotDev** [comment]
I was trying to upload using the absolute path, but now realize that is not how it needs to be done on mobile. It works good using fromFutureByteData, thanks!
